# Generated by Django 4.2.9 on 2024-01-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("last_reading", models.DecimalField(decimal_places=8, max_digits=18)),
                ("last_reading_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("reading", models.DecimalField(decimal_places=8, max_digits=18)),
                ("reading_time", models.DateTimeField()),
                (
                    "sensor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sensorapi.sensor",
                    ),
                ),
            ],
        ),
    ]
